[package]
name = "diro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1"
pest_derive = "2.1"
thiserror = "1.0"
rand = "0.8"

[workspace]
members = [
    "diro_py",
]